language: 
    - c
    - ruby

compiler: gcc

branches: # safelist
    only:
    - pubsub

os:
    - linux

install:
    #- sudo pip install codecov
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib; fi
    - sudo gem install ceedling

after_install:
    #- ceedling

script:
    #- cd tools/ceedling && ./test-all.sh
    - ceedling
    #- codecov

after_success:
    - bash <(curl -s https://codecov.io/bash)
