sudo: required
language: 
    - c

compiler: gcc

branches: # safelist
    only:
    - pubsub

os:
    - linux

install:
    - sudo gem install ceedling
    - sudo apt-get install lcov
    - sudo apt-get install cppcheck

script:
    - cd tools/ceedling && sudo ./test-all.sh
    - cd tools/analyzer && sudo ./cppcheck.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
